name:                 gb-synth
version:              0.1.0.0
visibility:           public
id:                   gb-synth-0.1.0.0-inplace
key:                  gb-synth-0.1.0.0-inplace
license:              MIT
maintainer:           gondola.bros.entertainment@gmail.com
author:               Gondola Bros Entertainment
synopsis:             Procedural music sequencer for GB games
description:
    A synthesis engine with tracker-style song DSL for generating
    retro game music and sound effects. Pure Haskell — no audio files,
    no samples, no DAW. Just math.

    Define songs declaratively with chords, patterns, sections, and
    instruments. Render to 16-bit mono PCM WAV at 22050 Hz.

category:             Sound
abi:                  inplace
exposed:              True
exposed-modules:
    GBSynth.Envelope GBSynth.Instrument GBSynth.Oscillator
    GBSynth.Pattern GBSynth.Render GBSynth.Song GBSynth.WAV

import-dirs:
    /Users/devontomlin/Documents/GitHub/gb-synth/dist-newstyle/build/aarch64-osx/ghc-9.6.7/gb-synth-0.1.0.0/build

library-dirs:
    /Users/devontomlin/Documents/GitHub/gb-synth/dist-newstyle/build/aarch64-osx/ghc-9.6.7/gb-synth-0.1.0.0/build

library-dirs-static:
    /Users/devontomlin/Documents/GitHub/gb-synth/dist-newstyle/build/aarch64-osx/ghc-9.6.7/gb-synth-0.1.0.0/build

dynamic-library-dirs:
    /Users/devontomlin/Documents/GitHub/gb-synth/dist-newstyle/build/aarch64-osx/ghc-9.6.7/gb-synth-0.1.0.0/build

data-dir:             /Users/devontomlin/Documents/GitHub/gb-synth/.
hs-libraries:         HSgb-synth-0.1.0.0-inplace
depends:              base-4.18.3.0 bytestring-0.11.5.4 containers-0.6.7
haddock-interfaces:
    /Users/devontomlin/Documents/GitHub/gb-synth/dist-newstyle/build/aarch64-osx/ghc-9.6.7/gb-synth-0.1.0.0/doc/html/gb-synth/gb-synth.haddock

haddock-html:
    /Users/devontomlin/Documents/GitHub/gb-synth/dist-newstyle/build/aarch64-osx/ghc-9.6.7/gb-synth-0.1.0.0/doc/html/gb-synth
